export const predefinedEvents = {
    CONNECT: 'connect',
}

export const events = {
    JOIN_ROOM: 'JOIN_ROOM',
    CREATE_ROOM: 'CREATE_ROOM',
    ROOM_NOT_EXISTS: 'ROOM_NOT_EXISTS',
    ROOM_CREATED: 'ROOM_CREATED',
    SET_USERNAME: 'SET_USERNAME',
    USER_JOINED: 'USER_JOINED',
    USER_LEFT: 'USER_LEFT',
    USERNAME_EXIST: 'USERNAME_EXIST',
    JOIN_ROOM_SUCCESS: 'JOIN_ROOM_SUCCESS',

    SUBMIT_WORD: 'SUBMIT_WORD',
    WORD_SUBMITTED: 'WORD_SUBMITTED',
    REVEAL_WORDS: 'REVEAL_WORDS',
    VICTORY: 'VICTORY',
}